name: Neurocommand CI/CD

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - neurocommand
  pull_request:
    branches: 
      - main
      - neurocommand
    
env:
  DOCKERHUB_ORG: ${{ secrets.DOCKERHUB_ORG }}
  ORACLE_USER: ${{ secrets.ORACLE_USER }}
  ORACLE_NEURODESK_BUCKET: ${{ secrets.ORACLE_NEURODESK_BUCKET }}
  OS_PASSWORD: ${{ secrets.SWIFT_OS_PASSWORD }}
  OS_PROJECT_ID: ${{ secrets.SWIFT_OS_PROJECT_ID }}
  OS_USERNAME: ${{ secrets.SWIFT_OS_USERNAME }}
  OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_ID }}
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  upload_containers_simg:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.AUTOCOMMIT_FOR_NEUROCOMMAND }}
      # This token is from my (stebo85) account -> it allows the action to skip the branch protection so we can commit from here
      # https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name : Check if singularity container files exist in oracle cloud and build & upload if not there
      run: /bin/bash .github/workflows/upload_containers_simg.sh
    - name: Auto commit changes to applist.json
      uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit-action
    - name: "Run if changes found to applist.json"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: |
          curl -X POST https://api.github.com/repos/NeuroDesk/neurodesk.github.io/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "NeuroDesk/neurocommand applist.json update"}'
  test_neurocommand:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test neurocommand version
      run: /bin/bash .github/workflows/test_neurocommand.sh
#   initiate-neurodesktop-build:
#     needs: [test_neurocommand]
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Dispatch initiating repository event
#         run: |
#           curl -X POST https://api.github.com/repos/NeuroDesk/neurodesktop/dispatches \
#           -H 'Accept: application/vnd.github.v3+json' \
#           -u ${{ secrets.ACCESS_TOKEN }} \
#           --data '{"event_type": "neurocommand update", "client_payload": { "GITHUB_REPOSITORY": "'"$GITHUB_REPOSITORY"'", "GITHUB_REPOSITORY_NAME": "'"${{ github.event.repository.name }}"'", "GITHUB_SHA": "'"$GITHUB_SHA"'" }}'
