name: push-to-vnm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: NeuroDesk/vnm
          token: ${{secrets.VNM_NEURODESK}}
          persist-credentials: false
          fetch-depth: 0
      - name: Setup git config
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "actions@github.com"
          git config pull.ff only
      - name: Setup git remotes
        run: |
          git remote add subtree https://vnm-neurodesk:${{secrets.VNM_NEURODESK}}@github.com/NeuroDesk/neurodesk.git
          git remote add upstream https://vnm-neurodesk:${{secrets.VNM_NEURODESK}}@github.com/NeuroDesk/vnm.git
      - name: Git status
        run:  git status
      - name: Git diff
        run: git diff
      - name: Pull neurodesk into vnm/neurodesk
        run:  git subtree pull --prefix neurodesk subtree master --squash
      - name: Push to vnm
        run:  git push upstream master
